import type {
  FavoriteTeam,
  League,
  MatchDetail,
  MatchLog,
  MvpVote,
  Player,
  Review,
  Sport,
  Stadium,
  Tag,
  Team,
  UserDetail,
} from "./matchlog-api";

export const currentUser: UserDetail = {
  id: "user-me",
  email: "easyh@gamelog.local",
  displayName: "easyh",
  avatarUrl: null,
  bio: "홈 응원석과 원정석의 공기를 모두 기록하는 팬.",
  primaryTeam: {
    id: "team-fc-seoul",
    sportId: "sport-football",
    leagueId: "league-k1",
    name: "FC Seoul",
    shortName: "SEO",
    slug: "fc-seoul",
  },
};

export const users: UserDetail[] = [
  currentUser,
  {
    id: "user-ana",
    email: "ana@gamelog.local",
    displayName: "ana",
    avatarUrl: null,
    bio: "스코어보다 장면을 오래 기억합니다.",
    primaryTeam: null,
  },
  {
    id: "user-min",
    email: "min@gamelog.local",
    displayName: "min",
    avatarUrl: null,
    bio: "야구장 외야석 수집가.",
    primaryTeam: null,
  },
  {
    id: "user-jun",
    email: "jun@gamelog.local",
    displayName: "jun",
    avatarUrl: null,
    bio: "원정 버스에서 쓰는 짧은 경기 일기.",
    primaryTeam: {
      id: "team-jeonbuk",
      sportId: "sport-football",
      leagueId: "league-k1",
      name: "Jeonbuk Hyundai Motors",
      shortName: "JEO",
      slug: "jeonbuk-hyundai",
    },
  },
  {
    id: "user-soo",
    email: "soo@gamelog.local",
    displayName: "soo",
    avatarUrl: null,
    bio: "중립석에서 전술과 분위기를 같이 봅니다.",
    primaryTeam: null,
  },
  {
    id: "user-hae",
    email: "hae@gamelog.local",
    displayName: "hae",
    avatarUrl: null,
    bio: "좋았던 장면만 태그로 남기는 편.",
    primaryTeam: {
      id: "team-lg",
      sportId: "sport-baseball",
      leagueId: "league-kbo",
      name: "LG Twins",
      shortName: "LGT",
      slug: "lg-twins",
    },
  },
];

export const sports: Sport[] = [
  { id: "sport-football", name: "Football", slug: "football" },
  { id: "sport-baseball", name: "Baseball", slug: "baseball" },
  { id: "sport-esports", name: "eSports", slug: "esports" },
];

export const leagues: League[] = [
  {
    id: "league-k1",
    sportId: "sport-football",
    name: "K League 1",
    country: "KR",
    slug: "k-league-1",
  },
  {
    id: "league-kbo",
    sportId: "sport-baseball",
    name: "KBO",
    country: "KR",
    slug: "kbo",
  },
  {
    id: "league-lck",
    sportId: "sport-esports",
    name: "LCK",
    country: "KR",
    slug: "lck",
  },
];

export const teams: Team[] = [
  {
    id: "team-fc-seoul",
    sportId: "sport-football",
    leagueId: "league-k1",
    name: "FC Seoul",
    shortName: "SEO",
    slug: "fc-seoul",
  },
  {
    id: "team-jeonbuk",
    sportId: "sport-football",
    leagueId: "league-k1",
    name: "Jeonbuk Hyundai Motors",
    shortName: "JEO",
    slug: "jeonbuk-hyundai",
  },
  {
    id: "team-doosan",
    sportId: "sport-baseball",
    leagueId: "league-kbo",
    name: "Doosan Bears",
    shortName: "DOO",
    slug: "doosan-bears",
  },
  {
    id: "team-lg",
    sportId: "sport-baseball",
    leagueId: "league-kbo",
    name: "LG Twins",
    shortName: "LGT",
    slug: "lg-twins",
  },
  {
    id: "team-t1",
    sportId: "sport-esports",
    leagueId: "league-lck",
    name: "T1",
    shortName: "T1",
    slug: "t1",
  },
  {
    id: "team-geng",
    sportId: "sport-esports",
    leagueId: "league-lck",
    name: "Gen.G",
    shortName: "GEN",
    slug: "gen-g",
  },
];

export const favoriteTeams: FavoriteTeam[] = [
  {
    id: "favorite-team-fc-seoul",
    userId: "user-me",
    sport: sports[0],
    league: leagues[0],
    team: teams[0],
    createdAt: "2026-06-01T00:00:00.000Z",
  },
  {
    id: "favorite-team-doosan",
    userId: "user-me",
    sport: sports[1],
    league: leagues[1],
    team: teams[2],
    createdAt: "2026-06-01T00:00:00.000Z",
  },
  {
    id: "favorite-team-t1",
    userId: "user-me",
    sport: sports[2],
    league: leagues[2],
    team: teams[4],
    createdAt: "2026-06-01T00:00:00.000Z",
  },
];

export const stadiums: Stadium[] = [
  {
    id: "stadium-seoul-wc",
    name: "Seoul World Cup Stadium",
    city: "Seoul",
    country: "KR",
    latitude: 37.5683,
    longitude: 126.8972,
  },
  {
    id: "stadium-jamsil",
    name: "Jamsil Baseball Stadium",
    city: "Seoul",
    country: "KR",
    latitude: 37.5122,
    longitude: 127.0719,
  },
  {
    id: "stadium-lol-park",
    name: "LoL Park",
    city: "Seoul",
    country: "KR",
    latitude: 37.5711,
    longitude: 126.9835,
  },
];

export const players: Player[] = [
  {
    id: "player-seoul-10",
    sportId: "sport-football",
    currentTeamId: "team-fc-seoul",
    name: "Kim Hyun",
    slug: "kim-hyun",
  },
  {
    id: "player-seoul-7",
    sportId: "sport-football",
    currentTeamId: "team-fc-seoul",
    name: "Lee Jun",
    slug: "lee-jun",
  },
  {
    id: "player-jeonbuk-1",
    sportId: "sport-football",
    currentTeamId: "team-jeonbuk",
    name: "Park Min",
    slug: "park-min",
  },
  {
    id: "player-doosan-52",
    sportId: "sport-baseball",
    currentTeamId: "team-doosan",
    name: "Choi Won",
    slug: "choi-won",
  },
  {
    id: "player-lg-17",
    sportId: "sport-baseball",
    currentTeamId: "team-lg",
    name: "Moon Seong",
    slug: "moon-seong",
  },
  {
    id: "player-t1-mid",
    sportId: "sport-esports",
    currentTeamId: "team-t1",
    name: "Faker",
    slug: "faker",
  },
  {
    id: "player-geng-ad",
    sportId: "sport-esports",
    currentTeamId: "team-geng",
    name: "Ruler",
    slug: "ruler",
  },
];

const tags: Record<string, Tag> = {
  final: { id: "tag-final", name: "결승전", tagType: "OFFICIAL" },
  derby: { id: "tag-derby", name: "라이벌전", tagType: "OFFICIAL" },
  best: { id: "tag-best", name: "올해최고", tagType: "USER" },
  away: { id: "tag-away", name: "원정응원", tagType: "USER" },
  comeback: { id: "tag-comeback", name: "역전승", tagType: "USER" },
};

export const mockTags = tags;

export const matches: MatchDetail[] = [
  {
    id: "match-seoul-jeonbuk",
    sport: sports[0],
    league: leagues[0],
    stadium: stadiums[0],
    homeTeam: teams[0],
    awayTeam: teams[1],
    matchDate: "2026-06-21T10:00:00.000Z",
    status: "FINAL",
    score: { home: 3, away: 2 },
    averageRating: 4.7,
    reviewCount: 832,
  },
  {
    id: "match-doosan-lg",
    sport: sports[1],
    league: leagues[1],
    stadium: stadiums[1],
    homeTeam: teams[2],
    awayTeam: teams[3],
    matchDate: "2026-06-18T09:30:00.000Z",
    status: "FINAL",
    score: { home: 5, away: 4 },
    averageRating: 4.3,
    reviewCount: 312,
  },
  {
    id: "match-t1-geng",
    sport: sports[2],
    league: leagues[2],
    stadium: stadiums[2],
    homeTeam: teams[4],
    awayTeam: teams[5],
    matchDate: "2026-06-29T08:00:00.000Z",
    status: "SCHEDULED",
    score: { home: null, away: null },
    averageRating: 0,
    reviewCount: 0,
  },
  {
    id: "match-jeonbuk-seoul",
    sport: sports[0],
    league: leagues[0],
    stadium: stadiums[0],
    homeTeam: teams[1],
    awayTeam: teams[0],
    matchDate: "2026-05-30T10:00:00.000Z",
    status: "FINAL",
    score: { home: 1, away: 1 },
    averageRating: 3.9,
    reviewCount: 144,
  },
];

export const logs: MatchLog[] = [
  {
    id: "log-seoul-jeonbuk",
    userId: "user-me",
    match: matches[0],
    watchedAt: "2026-06-21T10:05:00.000Z",
    watchType: "IN_PERSON",
    supportingTeam: teams[0],
    fanPerspective: "HOME_FAN",
    attendanceVerified: false,
  },
  {
    id: "log-doosan-lg",
    userId: "user-me",
    match: matches[1],
    watchedAt: "2026-06-18T09:30:00.000Z",
    watchType: "LIVE",
    supportingTeam: teams[2],
    fanPerspective: "HOME_FAN",
    attendanceVerified: false,
  },
];

export const reviews: Review[] = [
  {
    id: "review-me-seoul",
    matchId: "match-seoul-jeonbuk",
    user: currentUser,
    rating: 4.5,
    title: "첫 골 이후 경기장이 바뀌었다",
    body: "역전골 순간의 함성까지 오래 남을 경기. 홈팀 팬으로는 올해 가장 선명한 기억이다.",
    spoiler: false,
    emotion: "MOVED",
    fanPerspective: "HOME_FAN",
    tags: [tags.derby, tags.best, tags.comeback],
    likeCount: 42,
    likedByMe: false,
    createdAt: "2026-06-21T13:20:00.000Z",
    updatedAt: "2026-06-21T13:20:00.000Z",
  },
  {
    id: "review-ana-seoul",
    matchId: "match-seoul-jeonbuk",
    user: users[1],
    rating: 4,
    title: "패배했지만 원정석도 뜨거웠다",
    body: "결과는 아쉬웠지만 후반 압박과 골키퍼 선방은 충분히 기억할 만했다.",
    spoiler: true,
    emotion: "TENSE",
    fanPerspective: "AWAY_FAN",
    tags: [tags.derby, tags.away],
    likeCount: 31,
    likedByMe: true,
    createdAt: "2026-06-21T14:10:00.000Z",
    updatedAt: "2026-06-21T14:10:00.000Z",
  },
  {
    id: "review-min-baseball",
    matchId: "match-doosan-lg",
    user: users[2],
    rating: 4.5,
    title: "9회가 만든 잠실의 밤",
    body: "라이브로 봤는데도 현장 소리가 들리는 듯했다. 다시 보고 싶은 경기.",
    spoiler: false,
    emotion: "HAPPY",
    fanPerspective: "NEUTRAL_FAN",
    tags: [tags.best],
    likeCount: 18,
    likedByMe: false,
    createdAt: "2026-06-18T12:40:00.000Z",
    updatedAt: "2026-06-18T12:40:00.000Z",
  },
  {
    id: "review-jun-seoul-1",
    matchId: "match-seoul-jeonbuk",
    user: users[3],
    rating: 3.5,
    title: null,
    body: "원정 입장에서는 마지막 15분이 너무 길었다. 그래도 전반 압박은 좋았다.",
    spoiler: false,
    emotion: "ANGRY",
    fanPerspective: "AWAY_FAN",
    tags: [tags.derby, tags.away],
    likeCount: 9,
    likedByMe: false,
    createdAt: "2026-06-21T15:05:00.000Z",
    updatedAt: "2026-06-21T15:05:00.000Z",
  },
  {
    id: "review-soo-seoul-neutral",
    matchId: "match-seoul-jeonbuk",
    user: users[4],
    rating: 5,
    title: null,
    body: "중립으로 봐도 템포, 득점, 분위기가 모두 좋았다. 다시 틀어도 지루하지 않을 경기.",
    spoiler: false,
    emotion: "HAPPY",
    fanPerspective: "NEUTRAL_FAN",
    tags: [tags.best, tags.derby],
    likeCount: 27,
    likedByMe: true,
    createdAt: "2026-06-21T15:30:00.000Z",
    updatedAt: "2026-06-21T15:30:00.000Z",
  },
  {
    id: "review-hae-seoul-other",
    matchId: "match-seoul-jeonbuk",
    user: users[5],
    rating: 4,
    title: null,
    body: "응원팀 경기는 아니지만 경기장 에너지가 압도적이었다. 라이벌전은 확실히 다르다.",
    spoiler: false,
    emotion: "MOVED",
    fanPerspective: "OTHER_TEAM_FAN",
    tags: [tags.derby],
    likeCount: 13,
    likedByMe: false,
    createdAt: "2026-06-21T16:00:00.000Z",
    updatedAt: "2026-06-21T16:00:00.000Z",
  },
  {
    id: "review-me-seoul-short",
    matchId: "match-seoul-jeonbuk",
    user: currentUser,
    rating: 5,
    title: null,
    body: "재관람해도 역전 장면에서 소름이 돋는다.",
    spoiler: false,
    emotion: "HAPPY",
    fanPerspective: "HOME_FAN",
    tags: [tags.best],
    likeCount: 16,
    likedByMe: false,
    createdAt: "2026-06-22T02:20:00.000Z",
    updatedAt: "2026-06-22T02:20:00.000Z",
  },
  {
    id: "review-ana-seoul-low",
    matchId: "match-seoul-jeonbuk",
    user: users[1],
    rating: 2.5,
    title: null,
    body: "결과보다 수비 집중력이 무너진 장면이 계속 떠오른다.",
    spoiler: false,
    emotion: "SHOCKED",
    fanPerspective: "AWAY_FAN",
    tags: [tags.away],
    likeCount: 7,
    likedByMe: false,
    createdAt: "2026-06-22T03:10:00.000Z",
    updatedAt: "2026-06-22T03:10:00.000Z",
  },
  {
    id: "review-soo-seoul-mid",
    matchId: "match-seoul-jeonbuk",
    user: users[4],
    rating: 3,
    title: null,
    body: "하이라이트는 좋았지만 전체적으로는 거친 장면이 많아 호불호가 갈릴 듯하다.",
    spoiler: false,
    emotion: "TENSE",
    fanPerspective: "NEUTRAL_FAN",
    tags: [tags.derby],
    likeCount: 5,
    likedByMe: false,
    createdAt: "2026-06-22T04:15:00.000Z",
    updatedAt: "2026-06-22T04:15:00.000Z",
  },
  {
    id: "review-me-baseball",
    matchId: "match-doosan-lg",
    user: currentUser,
    rating: 3.5,
    title: null,
    body: "응원팀 경기는 아니지만 9회 흐름 하나로 충분히 남길 만했다.",
    spoiler: false,
    emotion: "TENSE",
    fanPerspective: "OTHER_TEAM_FAN",
    tags: [tags.comeback],
    likeCount: 11,
    likedByMe: false,
    createdAt: "2026-06-18T13:30:00.000Z",
    updatedAt: "2026-06-18T13:30:00.000Z",
  },
  {
    id: "review-hae-baseball-away",
    matchId: "match-doosan-lg",
    user: users[5],
    rating: 2.5,
    title: null,
    body: "LG 팬으로는 아쉬운 밤. 찬스가 많았는데 한 끗이 부족했다.",
    spoiler: false,
    emotion: "ANGRY",
    fanPerspective: "AWAY_FAN",
    tags: [],
    likeCount: 4,
    likedByMe: false,
    createdAt: "2026-06-18T14:00:00.000Z",
    updatedAt: "2026-06-18T14:00:00.000Z",
  },
  {
    id: "review-soo-baseball-home",
    matchId: "match-doosan-lg",
    user: users[4],
    rating: 4,
    title: null,
    body: "홈 관중의 리듬이 살아난 순간부터 경기가 다른 톤으로 흘렀다.",
    spoiler: false,
    emotion: "HAPPY",
    fanPerspective: "HOME_FAN",
    tags: [tags.comeback],
    likeCount: 8,
    likedByMe: true,
    createdAt: "2026-06-18T14:30:00.000Z",
    updatedAt: "2026-06-18T14:30:00.000Z",
  },
  {
    id: "review-jun-jeonbuk-seoul",
    matchId: "match-jeonbuk-seoul",
    user: users[3],
    rating: 3,
    title: null,
    body: "무승부라는 결과보다 서로 조심스러웠던 운영이 더 기억에 남는다.",
    spoiler: false,
    emotion: "TENSE",
    fanPerspective: "HOME_FAN",
    tags: [tags.derby],
    likeCount: 6,
    likedByMe: false,
    createdAt: "2026-05-30T13:00:00.000Z",
    updatedAt: "2026-05-30T13:00:00.000Z",
  },
  {
    id: "review-me-jeonbuk-seoul",
    matchId: "match-jeonbuk-seoul",
    user: currentUser,
    rating: 3.5,
    title: null,
    body: "원정에서 승점을 가져온 건 좋지만, 공격 전개는 조금 더 날카로웠으면 했다.",
    spoiler: false,
    emotion: "MOVED",
    fanPerspective: "AWAY_FAN",
    tags: [tags.away],
    likeCount: 12,
    likedByMe: false,
    createdAt: "2026-05-30T13:20:00.000Z",
    updatedAt: "2026-05-30T13:20:00.000Z",
  },
];

export const mvpVotes: MvpVote[] = [
  {
    id: "vote-me-seoul",
    matchId: "match-seoul-jeonbuk",
    userId: "user-me",
    player: players[0],
    createdAt: "2026-06-21T13:30:00.000Z",
    updatedAt: "2026-06-21T13:30:00.000Z",
  },
  {
    id: "vote-ana-seoul",
    matchId: "match-seoul-jeonbuk",
    userId: "user-ana",
    player: players[2],
    createdAt: "2026-06-21T14:30:00.000Z",
    updatedAt: "2026-06-21T14:30:00.000Z",
  },
  {
    id: "vote-min-baseball",
    matchId: "match-doosan-lg",
    userId: "user-min",
    player: players[3],
    createdAt: "2026-06-18T13:00:00.000Z",
    updatedAt: "2026-06-18T13:00:00.000Z",
  },
];
